import Foundation

/// Generates the Xcode Run Script Build Phase text and the helper packaging
/// script used for after-build packaging and scheduled builds.
///
/// Important: the Run Script only packages the already-built `.app` — it never
/// invokes `xcodebuild` again, which avoids build loops.
enum ScriptGenerator {
    /// Text the user pastes into Target → Build Phases → New Run Script Phase.
    static func runScriptPhase() -> String {
        """
        # iOS Build Manager – package after Xcode build (no xcodebuild inside).
        # Place in: Target → Build Phases → New Run Script Phase.
        # Only packages the already-built app for device builds; skips simulator/Mac
        # so it never re-enters the build (no build loops).

        if [ "$PLATFORM_NAME" != "iphoneos" ]; then
            exit 0
        fi

        APP_PATH="${BUILT_PRODUCTS_DIR}/${FULL_PRODUCT_NAME}"
        HELPER="$HOME/Library/Application Support/iOSBuildManager/package-ipa.sh"

        if [ ! -x "$HELPER" ]; then
            echo "warning: iOS Build Manager helper not found at \\\"$HELPER\\\" — skipping IPA packaging."
            exit 0
        fi

        "$HELPER" "$APP_PATH" "${PRODUCT_NAME}" "${MARKETING_VERSION}" "${CURRENT_PROJECT_VERSION}"
        """
    }

    /// The helper packaging script that creates Payload/, zips to .ipa, and
    /// refreshes latest.ipa in iCloud Builds.
    static let helperScriptContent: String = """
        #!/bin/bash
        # package-ipa.sh — packages a built .app into an .ipa and copies it to
        # iCloud Builds so it can be installed via SideStore / AltStore / Sideloadly.
        # Called by the Xcode Run Script phase or by iOS Build Manager.
        set -euo pipefail

        APP_PATH="${1:?usage: package-ipa.sh <app-path> [name] [version] [build]}"
        APP_NAME="${2:-$(basename "$APP_PATH" .app)}"
        VERSION="${3:-0.0.0}"
        BUILD="${4:-0}"

        OUTPUT_DIR="$HOME/Library/Mobile Documents/com~apple~CloudDocs/iOS Builds"
        mkdir -p "$OUTPUT_DIR"

        TMP="$(mktemp -d)"
        trap 'rm -rf "$TMP"' EXIT
        mkdir -p "$TMP/Payload"
        cp -R "$APP_PATH" "$TMP/Payload/${APP_NAME}.app"

        SAFE_NAME="$(echo "$APP_NAME" | tr ' ' '_')"
        IPA="$OUTPUT_DIR/${SAFE_NAME}-${VERSION}-${BUILD}.ipa"
        rm -f "$IPA"
        ( cd "$TMP" && zip -rXq "$IPA" Payload )

        # Always refresh latest.ipa for SideStore / AltStore / Sideloadly.
        cp -f "$IPA" "$OUTPUT_DIR/latest.ipa"

        echo "IPA created: $IPA"
        echo "latest.ipa updated at: $OUTPUT_DIR/latest.ipa"
        """

    /// Writes the helper script into Application Support and makes it executable.
    @discardableResult
    static func installHelperScript() throws -> URL {
        AppPaths.ensureDirectories()
        let url = AppPaths.helperScriptURL
        try helperScriptContent.write(to: url, atomically: true, encoding: .utf8)
        try? FileManager.default.setAttributes([.posixPermissions: 0o755], ofItemAtPath: url.path)
        return url
    }

    /// Generates a self-contained scheduled-build script that runs `xcodebuild`
    /// headlessly and then packages the result via the helper script.
    static func generateScheduledBuildScript(for project: Project) -> String {
        let helper = AppPaths.helperScriptURL.path
        let derived = AppPaths.derivedData(for: project).path
        let quotedArgs = XcodeBuildService.buildArguments(for: project)
            .map { "\"" + $0.replacingOccurrences(of: "\"", with: "\\\"") + "\"" }
            .joined(separator: " ")

        return """
            #!/bin/bash
            # Auto-generated by iOS Build Manager. Runs a scheduled build, packages
            # the IPA, re-installs onto a connected device (best effort), and posts
            # a macOS notification so you know the 6-day refresh happened.
            set -uo pipefail

            notify() { /usr/bin/osascript -e "display notification \\"$2\\" with title \\"$1\\"" >/dev/null 2>&1 || true; }

            NAME="\(project.name)"

            if ! /usr/bin/xcodebuild \(quotedArgs); then
                notify "❌ $NAME scheduled build failed" "xcodebuild returned an error. Open iOS Build Manager → Logs."
                exit 1
            fi

            APP="$(/usr/bin/find "\(derived)/Build/Products" -maxdepth 2 -name "*.app" | head -n 1)"
            if [ -z "$APP" ]; then
                notify "❌ $NAME scheduled build failed" "No .app found in build products."
                exit 1
            fi

            PLIST="$APP/Info.plist"
            VER="$(/usr/bin/defaults read "$PLIST" CFBundleShortVersionString 2>/dev/null || echo 0.0.0)"
            NUM="$(/usr/bin/defaults read "$PLIST" CFBundleVersion 2>/dev/null || echo 0)"
            NAME="$(basename "$APP" .app)"

            if [ -x "\(helper)" ]; then
                "\(helper)" "$APP" "$NAME" "$VER" "$NUM"
            fi

            # Close the loop: if a device is connected, re-install so the app on the
            # phone keeps working past the previous signing's expiry.
            DEVICE_ID="$(/usr/bin/xcrun devicectl list devices 2>/dev/null | /usr/bin/grep -Eo '([0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}|[0-9A-Fa-f]{40})' | head -n 1)"
            if [ -n "$DEVICE_ID" ]; then
                if /usr/bin/xcrun devicectl device install app --device "$DEVICE_ID" "$APP" >/dev/null 2>&1; then
                    notify "✅ $NAME $VER ($NUM) installed" "Rebuilt and re-installed on your device."
                else
                    notify "✅ $NAME $VER ($NUM) built" "IPA is in iCloud. Device install failed — install manually."
                fi
            else
                notify "✅ $NAME $VER ($NUM) built" "IPA updated in iCloud. Connect your device to re-install."
            fi
            """
    }
}
